---
title: "markdown"
author: "grazieli"
date: "May 16, 2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

hoje e o ultimo de aulas desta coisa

```{r }
library(ggplot2)
wnv<- read.csv("C:/Users/workshop/Desktop/wnv.csv")
ggplot(data=wnv) +
  geom_histogram(aes(x=log(Total))) +
  labs(x='Total', y='Frequency')+
  scale_x_log10()

```

## Including Plots

You can also embed plots, for example:

```{r echo=FALSE}
library(lubridate)
mers<-read.csv("cases.csv")
mers$hospitalized[890]<-c('2015-02-20')
mers<-mers[-471,]

mers$onset2 <- ymd(mers$onset)
mers$hospitalized2 <- ymd(mers$hospitalized)
class(mers$onset2)
day0 <- min(na.omit(mers$onset2))
mers$epi.day <- as.numeric(mers$onset2 - day0)
library(ggplot2)

ggplot(data=mers) +
  geom_bar(mapping=aes(x=epi.day)) +
  labs(x='Epidemic day', y='Case count', title='Global count of MERS cases by date of symptom onset', 
   caption='Data from: https://github.com/rambaut/MERS-Cases/blob/gh-pages/data/cases.cvs')

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
